# Generated by Django 6.0.1 on 2026-04-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('casual', 'Casual'), ('formal', 'Formal'), ('running', 'Running')], max_length=50)),
            ],
        ),
    ]
